from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot

class Ui_Home(QObject):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(780, 574)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.upload_file_area = QtWidgets.QFrame(self.centralwidget)
        self.upload_file_area.setGeometry(QtCore.QRect(50, 70, 711, 91))
        self.upload_file_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upload_file_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upload_file_area.setObjectName("upload_file_area")
        self.select_description = QtWidgets.QLabel(self.upload_file_area)
        self.select_description.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.select_description.setFont(font)
        self.select_description.setWordWrap(True)
        self.select_description.setObjectName("select_description")
        self.path_indicator = QtWidgets.QLineEdit(self.upload_file_area)
        self.path_indicator.setGeometry(QtCore.QRect(10, 30, 571, 20))
        self.path_indicator.setObjectName("path_indicator")
        self.browse_btn = QtWidgets.QPushButton(self.upload_file_area)
        self.browse_btn.setGeometry(QtCore.QRect(610, 30, 71, 23))
        self.browse_btn.setObjectName("browse_btn")
        self.App_title = QtWidgets.QLabel(self.centralwidget)
        self.App_title.setGeometry(QtCore.QRect(50, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.App_title.setFont(font)
        self.App_title.setWordWrap(True)
        self.App_title.setObjectName("App_title")
        self.divider = QtWidgets.QFrame(self.centralwidget)
        self.divider.setGeometry(QtCore.QRect(0, 490, 811, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.divider.setFont(font)
        self.divider.setFrameShape(QtWidgets.QFrame.HLine)
        self.divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divider.setObjectName("divider")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 200, 711, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.preview_label = QtWidgets.QLabel(self.frame)
        self.preview_label.setGeometry(QtCore.QRect(30, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.preview_label.setFont(font)
        self.preview_label.setObjectName("preview_label")
        self.preview_window = QtWidgets.QLabel(self.frame)
        self.preview_window.setGeometry(QtCore.QRect(26, 50, 661, 211))
        self.preview_window.setFrameShape(QtWidgets.QFrame.Box)
        self.preview_window.setText("")
        self.preview_window.setObjectName("preview_window")
        self.generate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(640, 520, 121, 41))
        self.generate_btn.setStyleSheet("background-color: lightgreen")
        self.generate_btn.setObjectName("generate_btn")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menubar.setObjectName("menubar")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)

        self.retranslateUi(Home)
        self.browse_btn.clicked.connect(self.browseSlot)
        self.path_indicator.returnPressed.connect(self.returnedPressedSlot)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Linknoide"))
        self.select_description.setText(_translate("Home", "Select File"))
        self.browse_btn.setText(_translate("Home", "Browse"))
        self.App_title.setText(_translate("Home", "Linknoide"))
        self.preview_label.setText(_translate("Home", "Preview"))
        self.generate_btn.setText(_translate("Home", "Generate"))

    @pyqtSlot()
    def browseSlot(self):
        pass

    @pyqtSlot()
    def returnedPressedSlot(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())

