from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot
from window import Ui_Window
from model import Model
import sys
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

class HomeUIClass(Ui_Window):
    def __init__(self):
        '''Initialize the super class
        '''
        super().__init__()
        self.model = Model()
        
    def setupUi(self, MW):
        ''' Setup the UI of the super class, and add here code
        that relates to the way we want our UI to operate.
        '''
        super().setupUi(MW)

    def refreshAll(self):
        '''
        Updates the widgets whenever an interaction happens.
        Typically some interaction takes place, the UI responds,
        and informs the model of the change. Then this method
        is called, pulling from the model information that is
        updated in the GUI.
        '''
        self.path_indicator.setText(self.model.getFileName())
        self.preview_window.setText(self.model.getFileContents())
        self.generate_btn.setEnabled(True)

    def makeNetwork(self):
        #Load the data
        fileName = self.model.getFileName()
        df = pd.read_csv(fileName)

        #Automate using predictions for full scale version
        g = nx.DiGraph()

        #Add edges into the network
        for i, elrow in df.iterrows():
           g.add_edge(elrow[1], elrow[0])
        return g

    def subgraph(self, term):
        df = pd.read_csv("matt_test_network.csv")
        # automate using predictions for full scale version
        color = pd.DataFrame(
            data=['silver'] * len(df.index))
        df['color'] = color
        df_sub = df.loc[df['Origin'] == term]
        g = nx.DiGraph()
 
        # Add edges into network
        for i, elrow in df_sub.iterrows():
            g.add_edge(elrow[0], elrow[1], attr_dict=elrow[2:].to_dict(), weight=1/elrow['description'])
 
        # Manually add X and Y coords of nodes
        nodeList = {'NodeName': ['home', 'ht', 'work', 'daycare', 'coffee'], 'X': [70, 405, 835, 300, 750],
                'Y': [250, 300, 240, 450, 510]}
        nodeFrame = pd.DataFrame(data=nodeList)
        # add node properties
        for i, nlrow in nodeFrame.iterrows():
            g.node[nlrow[0]] = nlrow[1:].to_dict()
        return g

    # slot
    def pathSlot(self):
        ''' Called when the user enters a string in the line edit and
        presses the ENTER key.
        '''
        fileName =  self.path_indicator.text()
        if self.model.isValid(fileName):
            self.model.setFileName(self.path_indicator.text())
            self.refreshAll()
        else:
            m = QtWidgets.QMessageBox()
            m.setText("Invalid file name!\n" + fileName)
            m.setIcon(QtWidgets.QMessageBox.Warning)
            m.setStandardButtons(QtWidgets.QMessageBox.Ok
                                 | QtWidgets.QMessageBox.Cancel)
            m.setDefaultButton(QtWidgets.QMessageBox.Cancel)
            ret = m.exec_()
            self.path_indicator.setText("")
            self.refreshAll()
            self.debugPrint("Invalid file specified: " + fileName)

    # slot
    def browseSlot(self):
        ''' Called when the user presses the Browse button
        '''
        options = QtWidgets.QFileDialog.Options()
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
                        None,
                        "Select File",
                        "",
                        "All Files (*);;CSV Files (*.csv)",
                        options=options)
        if fileName:
            self.model.setFileName(fileName)
            self.refreshAll()

    # slot
    def generateSlot(self):
        ''' Called when the user presses the Generate button
        '''
        self.figure.clf()

        g = self.makeNetwork()

        #labels = nx.get_edge_attributes(g, elrow[2])
        nPos = nx.spring_layout(g)
        #nx.draw(g, pos)
        nx.draw_networkx(g, pos=nPos, node_size=500, alpha=0.5, node_color='r', edge_color='silver', arrows=True, with_labels=True)
        nx.draw_networkx_edge_labels(g, pos=nPos, font_color="black", alpha=.2)
        plt.title('Project Activity Sequence', size=13)
        plt.axis("off")
        self.canvas.draw()
        self.generate_btn.setEnabled(False)
        


def main():
    """
    This is the MAIN ENTRY POINT of our application. The code at the end
    of the mainwindow.py script will not be executed, since this script is now
    our main program. We have simply copied the code from mainwindow.py here
    since it was automatically generated by '''pyuic5'''.

    """
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = HomeUIClass()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

main()